---
  - name: Install Metricbeat
    hosts: webservers
    become: true
    tasks:
      # Command Module
    - name: Download Metricbeat
      command: curl -L -O https://artifacts.elastic.co/dowloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      # Command module
    - name: Install Metricbeat
       command: dpkg -i metricbeat-7.6.1-amd64.deb

      # Copy module
    - name: Drop in Metricbeat Config
      copy:
        src: etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

      # Use command Module
    - name: enable and configure docker module for metricbeat
      command: metricbeat modules enable docker

      # Use Command Module
    - name: setup metricbeat
      command: metricbeat setup

      # Use Command Module
    - name: start metricbeat
      sudo service metricbeat start    
        